### ISSUE TITLE
Asynchronous _on_message handler error

### ISSUE THREAD

**Issue by Allineer** [wialon/gmqtt#63] opened 2019-10-02 04:25 UTC
@Lenka42, we have a problem :(
```
/usr/local/lib/python3.7/site-packages/gmqtt/mqtt/handler.py:353: RuntimeWarning: coroutine 'blablabla._on_message' was never awaited
  self.on_message(self, print_topic, packet, 1, properties)
```

**Comment by Lenka42** [comment] 2019-10-02 08:28
@Allineer There was a problem with asynchronous callbacks in client with `optimistic_acknowledgement=True`. Thanks for reporting this,  fixed in version 0.4.3

**Comment by DurandA** [comment] 2019-10-03 05:00
@Lenka42 The issue is still present. I just reinstalled _gmqtt_ from git master.

**Comment by DurandA** [comment] 2019-10-03 05:28
@Lenka42 The error is still present when using `functools.partial`.

**Closed** 2019-10-17 12:10 UTC
